### ISSUE TITLE
Youtube-Viewers

### ISSUE THREAD

**Issue by junormeshud** [Airkek/Airkek#1]
Hey Airkek, 
which good paid proxies used you for the bot? and why is Youtube-Viewers Archived?

**Comment by Airkek** [comment]
> why is Youtube-Viewers Archived?
project is discontinued

> which good paid proxies used you for the bot?
https://awmproxy.com/

**Comment by junormeshud** [comment]
Thanks... but what's the reason :( 😰 i hope you will always help us 🥺

**Comment by Airkek** [comment]
> what's the reason 

my shitty legacy code

**Comment by junormeshud** [comment]
maybe you can do an update for the last time please? :(
